---
- name: Create an Incident in ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://infosystechnologiesltdsvsdemo17.service-now.com"
    servicenow_user: "Ansible_User"
    servicenow_password: "hIoXeL1MvJwz1}CwLw,4hjIFiGFTB[SL_W%v-"
    incident_details:
      short_description: "Incident from AWX"
      description: "This incident was created via AWX integration."
      priority: "2"

  tasks:
    - name: Create an Incident in ServiceNow
      uri:
        url: "https://infosystechnologiesltdsvsdemo17.service-now.com/api/now/table/incident"
        method: POST
        user: "Ansible_User"
        password: "hIoXeL1MvJwz1}CwLw,4hjIFiGFTB[SL_W%v-"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body: "{{ incident_details | to_json }}"
        body_format: json
        return_content: yes
        validate_certs: no
      register: result

    - name: Print the response status code
      debug:
        msg: "Status code: {{ result.status }}"

    - name: Print the response content
      debug:
        var: result.json

    - name: Print the incident number if created
      debug:
        msg: "Created incident number: {{ result.json.result.number }}"
      when: result.json.result.number is defined
